package EditorialApp;

/**
* EditorialApp/EditorialHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from editorialApp.idl
* jueves 9 de mayo de 2019 10:26:46 PM COT
*/

public final class EditorialHolder implements org.omg.CORBA.portable.Streamable
{
  public EditorialApp.Editorial value = null;

  public EditorialHolder ()
  {
  }

  public EditorialHolder (EditorialApp.Editorial initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EditorialApp.EditorialHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EditorialApp.EditorialHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EditorialApp.EditorialHelper.type ();
  }

}
