package EditorialApp;


/**
* EditorialApp/Editorial.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from editorialApp.idl
* jueves 9 de mayo de 2019 10:26:46 PM COT
*/

public interface Editorial extends EditorialOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Editorial
