package EditorialApp;


/**
* EditorialApp/EditorialOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from editorialApp.idl
* jueves 9 de mayo de 2019 10:26:46 PM COT
*/

public interface EditorialOperations 
{
  boolean insertarEditorial (int id_editorial, String ed_editorial);
  boolean actualizarEditorial (int id_editorial, String ed_editorial);
  boolean eliminarEditorial (int id_editorial, String ed_editorial);
  void shutdown ();
} // interface EditorialOperations
