package AlquilerApp;


/**
* AlquilerApp/AlquilerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alquilerApp.idl
* jueves 9 de mayo de 2019 11:31:33 PM COT
*/

public interface AlquilerOperations 
{
  boolean insertarAlquiler (int id_alquiler, int id_lector, int id_libro);
  boolean actualizarAlquiler (int id_alquiler, int id_lector, int id_libro);
  boolean eliminarAlquiler (int id_alquiler);
  void shutdown ();
} // interface AlquilerOperations
