package AlquilerApp;


/**
* AlquilerApp/AlquilerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alquilerApp.idl
* jueves 9 de mayo de 2019 11:31:33 PM COT
*/

abstract public class AlquilerHelper
{
  private static String  _id = "IDL:AlquilerApp/Alquiler:1.0";

  public static void insert (org.omg.CORBA.Any a, AlquilerApp.Alquiler that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AlquilerApp.Alquiler extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AlquilerApp.AlquilerHelper.id (), "Alquiler");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AlquilerApp.Alquiler read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AlquilerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AlquilerApp.Alquiler value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AlquilerApp.Alquiler narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AlquilerApp.Alquiler)
      return (AlquilerApp.Alquiler)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AlquilerApp._AlquilerStub stub = new AlquilerApp._AlquilerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AlquilerApp.Alquiler unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AlquilerApp.Alquiler)
      return (AlquilerApp.Alquiler)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AlquilerApp._AlquilerStub stub = new AlquilerApp._AlquilerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
