package AlquilerApp;


/**
* AlquilerApp/Alquiler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AlquilerApp.idl
* jueves 9 de mayo de 2019 11:47:31 PM COT
*/

public interface Alquiler extends AlquilerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Alquiler
