package LibroApp;


/**
* LibroApp/LibroPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibroApp.idl
* jueves 9 de mayo de 2019 11:09:42 PM COT
*/

public abstract class LibroPOA extends org.omg.PortableServer.Servant
 implements LibroApp.LibroOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarLibro", new java.lang.Integer (0));
    _methods.put ("actualizarLibro", new java.lang.Integer (1));
    _methods.put ("eliminarLibro", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // LibroApp/Libro/insertarLibro
       {
         String titulo = in.read_wstring ();
         String autor = in.read_wstring ();
         String categoria = in.read_wstring ();
         String editorial = in.read_wstring ();
         String paginas = in.read_wstring ();
         String descripcion = in.read_wstring ();
         String portada = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarLibro (titulo, autor, categoria, editorial, paginas, descripcion, portada);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // LibroApp/Libro/actualizarLibro
       {
         int asin = in.read_long ();
         String titulo = in.read_wstring ();
         String autor = in.read_wstring ();
         String categoria = in.read_wstring ();
         String editorial = in.read_wstring ();
         String paginas = in.read_wstring ();
         String descripcion = in.read_wstring ();
         String portada = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarLibro (asin, titulo, autor, categoria, editorial, paginas, descripcion, portada);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // LibroApp/Libro/eliminarLibro
       {
         int asin = in.read_long ();
         String titulo = in.read_wstring ();
         String autor = in.read_wstring ();
         String categoria = in.read_wstring ();
         String editorial = in.read_wstring ();
         String paginas = in.read_wstring ();
         String descripcion = in.read_wstring ();
         String portada = in.read_wstring ();
         boolean $result = false;
         $result = this.eliminarLibro (asin, titulo, autor, categoria, editorial, paginas, descripcion, portada);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // LibroApp/Libro/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:LibroApp/Libro:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Libro _this() 
  {
    return LibroHelper.narrow(
    super._this_object());
  }

  public Libro _this(org.omg.CORBA.ORB orb) 
  {
    return LibroHelper.narrow(
    super._this_object(orb));
  }


} // class LibroPOA
