package LibroApp;


/**
* LibroApp/LibroHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibroApp.idl
* jueves 9 de mayo de 2019 11:09:42 PM COT
*/

abstract public class LibroHelper
{
  private static String  _id = "IDL:LibroApp/Libro:1.0";

  public static void insert (org.omg.CORBA.Any a, LibroApp.Libro that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LibroApp.Libro extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LibroApp.LibroHelper.id (), "Libro");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LibroApp.Libro read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LibroStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LibroApp.Libro value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LibroApp.Libro narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LibroApp.Libro)
      return (LibroApp.Libro)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LibroApp._LibroStub stub = new LibroApp._LibroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LibroApp.Libro unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LibroApp.Libro)
      return (LibroApp.Libro)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LibroApp._LibroStub stub = new LibroApp._LibroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
