package LibroApp;


/**
* LibroApp/LibroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibroApp.idl
* jueves 9 de mayo de 2019 11:09:42 PM COT
*/

public interface LibroOperations 
{
  boolean insertarLibro (String titulo, String autor, String categoria, String editorial, String paginas, String descripcion, String portada);
  boolean actualizarLibro (int asin, String titulo, String autor, String categoria, String editorial, String paginas, String descripcion, String portada);
  boolean eliminarLibro (int asin, String titulo, String autor, String categoria, String editorial, String paginas, String descripcion, String portada);
  void shutdown ();
} // interface LibroOperations
