package AutorApp;


/**
* AutorApp/Autor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Autor.idl
* miércoles 8 de mayo de 2019 08:57:40 PM COT
*/

public interface Autor extends AutorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Autor
