package AutorApp;


/**
* AutorApp/AutorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Autor.idl
* miércoles 8 de mayo de 2019 08:57:40 PM COT
*/

abstract public class AutorHelper
{
  private static String  _id = "IDL:AutorApp/Autor:1.0";

  public static void insert (org.omg.CORBA.Any a, AutorApp.Autor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AutorApp.Autor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AutorApp.AutorHelper.id (), "Autor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AutorApp.Autor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AutorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AutorApp.Autor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AutorApp.Autor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AutorApp.Autor)
      return (AutorApp.Autor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AutorApp._AutorStub stub = new AutorApp._AutorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AutorApp.Autor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AutorApp.Autor)
      return (AutorApp.Autor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AutorApp._AutorStub stub = new AutorApp._AutorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
