package AutorApp;


/**
* AutorApp/AutorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Autor.idl
* miércoles 8 de mayo de 2019 08:57:40 PM COT
*/

public interface AutorOperations 
{
  boolean insertarPersona (String au_autor);
  boolean actualizarPersona (int au_idautor, String au_autor);
  boolean eliminarPersona (int au_idautor);
  void shutdown ();
} // interface AutorOperations
