package LectorApp;


/**
* LectorApp/Lector.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LectorApp.idl
* jueves 9 de mayo de 2019 10:51:39 PM COT
*/

public interface Lector extends LectorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Lector
