package LectorApp;


/**
* LectorApp/LectorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LectorApp.idl
* jueves 9 de mayo de 2019 10:51:39 PM COT
*/

public interface LectorOperations 
{
  boolean insertarLector (int dnilector, String nombre, String celular, String observacion);
  boolean actualizarLector (int dnilector, String nombre, String celular, String observacion);
  boolean eliminarLector (int dnilector, String nombre, String celular, String observacion);
  void shutdown ();
} // interface LectorOperations
