package LectorApp;


/**
* LectorApp/LectorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LectorApp.idl
* jueves 9 de mayo de 2019 10:51:39 PM COT
*/

abstract public class LectorHelper
{
  private static String  _id = "IDL:LectorApp/Lector:1.0";

  public static void insert (org.omg.CORBA.Any a, LectorApp.Lector that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LectorApp.Lector extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LectorApp.LectorHelper.id (), "Lector");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LectorApp.Lector read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LectorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LectorApp.Lector value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LectorApp.Lector narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LectorApp.Lector)
      return (LectorApp.Lector)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LectorApp._LectorStub stub = new LectorApp._LectorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LectorApp.Lector unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LectorApp.Lector)
      return (LectorApp.Lector)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LectorApp._LectorStub stub = new LectorApp._LectorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
