package LectorApp;


/**
* LectorApp/LectorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LectorApp.idl
* jueves 9 de mayo de 2019 10:51:39 PM COT
*/

public abstract class LectorPOA extends org.omg.PortableServer.Servant
 implements LectorApp.LectorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarLector", new java.lang.Integer (0));
    _methods.put ("actualizarLector", new java.lang.Integer (1));
    _methods.put ("eliminarLector", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // LectorApp/Lector/insertarLector
       {
         int dnilector = in.read_long ();
         String nombre = in.read_wstring ();
         String celular = in.read_wstring ();
         String observacion = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarLector (dnilector, nombre, celular, observacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // LectorApp/Lector/actualizarLector
       {
         int dnilector = in.read_long ();
         String nombre = in.read_wstring ();
         String celular = in.read_wstring ();
         String observacion = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarLector (dnilector, nombre, celular, observacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // LectorApp/Lector/eliminarLector
       {
         int dnilector = in.read_long ();
         String nombre = in.read_wstring ();
         String celular = in.read_wstring ();
         String observacion = in.read_wstring ();
         boolean $result = false;
         $result = this.eliminarLector (dnilector, nombre, celular, observacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // LectorApp/Lector/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:LectorApp/Lector:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Lector _this() 
  {
    return LectorHelper.narrow(
    super._this_object());
  }

  public Lector _this(org.omg.CORBA.ORB orb) 
  {
    return LectorHelper.narrow(
    super._this_object(orb));
  }


} // class LectorPOA
