package EditorialApp;


/**
* EditorialApp/EditorialPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from editorialApp.idl
* jueves 9 de mayo de 2019 10:26:46 PM COT
*/

public abstract class EditorialPOA extends org.omg.PortableServer.Servant
 implements EditorialApp.EditorialOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarEditorial", new java.lang.Integer (0));
    _methods.put ("actualizarEditorial", new java.lang.Integer (1));
    _methods.put ("eliminarEditorial", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // EditorialApp/Editorial/insertarEditorial
       {
         int id_editorial = in.read_long ();
         String ed_editorial = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarEditorial (id_editorial, ed_editorial);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // EditorialApp/Editorial/actualizarEditorial
       {
         int id_editorial = in.read_long ();
         String ed_editorial = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarEditorial (id_editorial, ed_editorial);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // EditorialApp/Editorial/eliminarEditorial
       {
         int id_editorial = in.read_long ();
         String ed_editorial = in.read_wstring ();
         boolean $result = false;
         $result = this.eliminarEditorial (id_editorial, ed_editorial);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // EditorialApp/Editorial/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EditorialApp/Editorial:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Editorial _this() 
  {
    return EditorialHelper.narrow(
    super._this_object());
  }

  public Editorial _this(org.omg.CORBA.ORB orb) 
  {
    return EditorialHelper.narrow(
    super._this_object(orb));
  }


} // class EditorialPOA
