package EditorialApp;


/**
* EditorialApp/EditorialHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from editorialApp.idl
* jueves 9 de mayo de 2019 10:26:46 PM COT
*/

abstract public class EditorialHelper
{
  private static String  _id = "IDL:EditorialApp/Editorial:1.0";

  public static void insert (org.omg.CORBA.Any a, EditorialApp.Editorial that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EditorialApp.Editorial extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EditorialApp.EditorialHelper.id (), "Editorial");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EditorialApp.Editorial read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EditorialStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EditorialApp.Editorial value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EditorialApp.Editorial narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EditorialApp.Editorial)
      return (EditorialApp.Editorial)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EditorialApp._EditorialStub stub = new EditorialApp._EditorialStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static EditorialApp.Editorial unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EditorialApp.Editorial)
      return (EditorialApp.Editorial)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EditorialApp._EditorialStub stub = new EditorialApp._EditorialStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
