package CategoriaApp;

/**
* CategoriaApp/CategoriaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CategoriaApp.idl
* jueves 9 de mayo de 2019 10:06:39 PM COT
*/

public final class CategoriaHolder implements org.omg.CORBA.portable.Streamable
{
  public CategoriaApp.Categoria value = null;

  public CategoriaHolder ()
  {
  }

  public CategoriaHolder (CategoriaApp.Categoria initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CategoriaApp.CategoriaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CategoriaApp.CategoriaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CategoriaApp.CategoriaHelper.type ();
  }

}
