package CategoriaApp;


/**
* CategoriaApp/CategoriaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CategoriaApp.idl
* jueves 9 de mayo de 2019 10:06:39 PM COT
*/

public interface CategoriaOperations 
{
  boolean insertarCategoria (int id_categoria, String ca_categoria);
  boolean actualizarCategoria (int id_categoria, String ca_categoria);
  boolean eliminarCategoria (int id_categoria, String ca_categoria);
  void shutdown ();
} // interface CategoriaOperations
