package CategoriaApp;


/**
* CategoriaApp/CategoriaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CategoriaApp.idl
* jueves 9 de mayo de 2019 10:06:39 PM COT
*/

abstract public class CategoriaHelper
{
  private static String  _id = "IDL:CategoriaApp/Categoria:1.0";

  public static void insert (org.omg.CORBA.Any a, CategoriaApp.Categoria that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CategoriaApp.Categoria extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CategoriaApp.CategoriaHelper.id (), "Categoria");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CategoriaApp.Categoria read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CategoriaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CategoriaApp.Categoria value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CategoriaApp.Categoria narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CategoriaApp.Categoria)
      return (CategoriaApp.Categoria)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CategoriaApp._CategoriaStub stub = new CategoriaApp._CategoriaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CategoriaApp.Categoria unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CategoriaApp.Categoria)
      return (CategoriaApp.Categoria)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CategoriaApp._CategoriaStub stub = new CategoriaApp._CategoriaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
