package CategoriaApp;


/**
* CategoriaApp/Categoria.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CategoriaApp.idl
* jueves 9 de mayo de 2019 10:06:39 PM COT
*/

public interface Categoria extends CategoriaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Categoria
